name: screensaver
description: >
  A customizable Flutter screen saver plugin that activates after user inactivity.
  Supports displaying images, animated GIFs, and videos — ideal for kiosk and display apps.
version: 1.0.4
homepage: https://sawin.com.np
repository: https://github.com/sawin0/screensaver

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:

topics:
  - screensaver
  - media
  - video
  - gif
  - image

#flutter:
# Example assets (uncomment and update as needed)
# assets:
#   - assets/images/sample.jpg
#   - assets/videos/demo.mp4
#   - assets/gifs/animated.gif
